export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_WORKERS = "GET_WORKERS";
export const WORKERS_LOADING = "WORKERS_LOADING";

export const FETCH_DATA_FULFILLED="FETCH_DATA_FULFILLED"
export const FETCH_DATA_REJECTED="FETCH_DATA_REJECTED"


export  const FETCH_WORK_FORCE ="FETCH_WORK_FORCE"
export  const WORK_FORCE_LOADING ="WORK_FORCE_LOADING"
export  const FETCH_ATTENDANCE ="FETCH_ATTENDANCE"
export  const ATTENDANCE_LOADING ="ATTENDANCE_LOADING"

export  const FETCH_GHOST_WORKER ="FETCH_WORK_FORCE"
export  const GHOST_WORKER_LOADING ="WORK_FORCE_LOADING"


export  const FETCH_All_STAT ="FETCH_ALL_STAT"
export  const ALL_STAT_LOADING ="ALL_STAT_LOADING"

export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';